AWSTemplateFormatVersion: '2010-09-09'
Description: Provisions AWS Serverless API resourcs for the Simple EC2 Inventory sample solution on AWS
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  AppName:
    Description: "Application Name"
    Type: String
    Default: simple-ec2-inventory
  EnvType:
    Description: "Environment type (eg, dev, qa, prod)"
    Type: String
    Default: dev
  DatabaseStackName:
    Description: "Name of the RDS CloudFormation stack to import parameters from"
    Type: String
    Default: ec2_inventory_db
  EC2TableName:
    Description: "EC2 Table name"
    Type: String
    Default: ec2
  PackageTableName:
    Description: "Package Table name"
    Type: String
    Default: package
  EC2PackageTableName:
    Description: "EC2-Package Table name"
    Type: String
    Default: ec2_package
  ApiStageName:
    Description: "API Stage Name"
    Type: String
    Default: dev
Globals:
  Function:
    Runtime: python3.6
    Timeout: 120
    MemorySize: 256
    AutoPublishAlias: live
    Environment:
      Variables:
        EC2_TABLE_NAME: !Ref EC2TableName
        PACKAGE_TABLE_NAME: !Ref PackageTableName
        EC2_PACKAGE_RPM_TABLE_NAME: !Ref EC2PackageTableName
        DB_NAME: 
          Fn::ImportValue: 
            !Sub "${DatabaseStackName}-DatabaseName"
        DB_CLUSTER_ARN: 
          Fn::ImportValue: 
              !Sub "${DatabaseStackName}-DatabaseClusterArn" 
        DB_CRED_SECRETS_STORE_ARN: 
          Fn::ImportValue: 
              !Sub "${DatabaseStackName}-DatabaseSecretArn" 
  Api:
    Name: !Sub "${EnvType}-${AppName}-api"
    EndpointConfiguration: REGIONAL
Resources:
  EC2InventoryAPI:
    Type: 'AWS::Serverless::Api'
    Properties:
        StageName: !Sub "${ApiStageName}"
  AddEC2InfoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Adds EC2 info to the inventory
      FunctionName: !Sub "${EnvType}-${AppName}-add-ec2-lambda"
      CodeUri: ../lambdas/
      Handler: add_ec2_info.handler
      Events:
        AMIPost:
          Type: Api
          Properties:
            Path: '/ec2/{aws_instance_id}'
            Method: post
            RestApiId: !Ref EC2InventoryAPI
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteSql
                - secretsmanager:GetSecretValue
              Resource: '*'
  GetEC2InfoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Retrieves EC2 info from the inventory
      FunctionName: !Sub "${EnvType}-${AppName}-get-ec2-lambda"
      CodeUri: ../lambdas/
      Handler: get_ec2_info.handler
      Events:
        AMIPost:
          Type: Api
          Properties:
            Path: '/ec2/{aws_instance_id}'
            Method: get
            RestApiId: !Ref EC2InventoryAPI
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - rds-data:ExecuteSql
                - secretsmanager:GetSecretValue
              Resource: '*'
Outputs:
  StackName:
    Description: API Stack Name
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub ${AWS::StackName}-StackName

  ApiEndpoint:
    Description: API Stage Endpoint
    Value: !Ref EC2InventoryAPI
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndPoint
